spring:
    sql:
        init:
            mode: "always"
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: never
    datasource:
        url: jdbc:h2:file:./database;SCHEMA=comere;database_to_upper=false